package cafedansadatabase;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.DefaultComboBoxModel;

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    * Class         EditDancer
    * File          EditDancer.java
    * Description   A class used to add new dancer
    * Platform      1.8.0_51-b16 ,NetBeans IDE 15;Windows 10
    * @author       <i>Abylay Dospayev</i>
    * Date          9/28/2022
    * History Log    
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
public class EditDancer extends javax.swing.JDialog {
    private Dancer newDancer;                       //City to be created
    private boolean error = false;              //Checking for errors in input
    private String errorMessage = "";           //Error message
    private final int MAX = 100;                //Max years of dancing 
    private final Color white = Color.WHITE;    //Def. background color for input textfield
    private final Color pink = Color.PINK;      //Background color for bad input textfield
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    * Class         EditDancer()
    * Description   Create an instance of the GUI form, set the default JButton,
    *               to be saveJButton, set icon image, centers form, and sets
    *               the JDialog form to modal 
    * @author       <i>Abylay Dospayev</i>
    * Date          9/28/2022   
    * @param        parent Frame
     *@param        modal Boolean
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    public EditDancer() {
        //super(parent, modal);
        initComponents();
        //set saveJButton as default
        this.getRootPane().setDefaultButton(savejButton);
        //set icon
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/cafedansadatabase/dancegroup1.jpg"));
        //center form
        this.setLocationRelativeTo(null);
        namejTextField.requestFocus(); //set focus to first jtextfield
        newDancer = null; 
        setAlwaysOnTop(true);
        setModal(true);
        stylejComboBox.setModel(new DefaultComboBoxModel(
                DancerGUI.STYLES));
        leveljComboBox.setModel(new DefaultComboBoxModel(
                DancerGUI.PROFICIENCIES));
    }
    
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Class         EditDancer() overloaded constructor
    * Description   Calls default contructor toreate an instance of the GUI
    *               form and populates the data fields for the seletcted dancer
    *               the JDialog form to modal 
    * @author       <i>Abylay Dospayev</i>
    * Date          9/28/2022
    * History Log 
    * @param        dancer Dancer
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    public EditDancer(Dancer dancer)
    {
        this(); //call the def constructor
        namejTextField.setText(dancer.getName());
        phonejTextField.setText(dancer.getPhone());
        emailjTextField.setText(dancer.getEmail());
        yearsjTextField.setText(String.valueOf(dancer.getYears()));
        namejTextField.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlejPanel = new javax.swing.JPanel();
        imagejLabel = new javax.swing.JLabel();
        titlejLabel = new javax.swing.JLabel();
        displayjPanel = new javax.swing.JPanel();
        namejLabel = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        stylejLabel = new javax.swing.JLabel();
        stylejComboBox = new javax.swing.JComboBox<>();
        leveljLabel = new javax.swing.JLabel();
        leveljComboBox = new javax.swing.JComboBox<>();
        yearsjLabel = new javax.swing.JLabel();
        yearsjTextField = new javax.swing.JTextField();
        phonejLabel = new javax.swing.JLabel();
        phonejTextField = new javax.swing.JTextField();
        emailjLabel = new javax.swing.JLabel();
        emailjTextField = new javax.swing.JTextField();
        controljPanel = new javax.swing.JPanel();
        savejButton = new javax.swing.JButton();
        canceljButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Dancer");
        setResizable(false);

        imagejLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafedansadatabase/dancegroup2.jpg"))); // NOI18N
        imagejLabel.setText("jLabel1");

        titlejLabel.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        titlejLabel.setText("Edit New Dancer");

        javax.swing.GroupLayout titlejPanelLayout = new javax.swing.GroupLayout(titlejPanel);
        titlejPanel.setLayout(titlejPanelLayout);
        titlejPanelLayout.setHorizontalGroup(
            titlejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titlejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        titlejPanelLayout.setVerticalGroup(
            titlejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagejLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlejPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titlejLabel)
                .addGap(32, 32, 32))
        );

        displayjPanel.setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        namejLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        namejLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        namejLabel.setText("Name of Dancer:");
        displayjPanel.add(namejLabel);

        namejTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                namejTextFieldFocusLost(evt);
            }
        });
        namejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namejTextFieldActionPerformed(evt);
            }
        });
        displayjPanel.add(namejTextField);

        stylejLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        stylejLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        stylejLabel.setText("Dance Style:");
        stylejLabel.setToolTipText("");
        displayjPanel.add(stylejLabel);

        stylejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stylejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stylejComboBoxActionPerformed(evt);
            }
        });
        displayjPanel.add(stylejComboBox);

        leveljLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        leveljLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        leveljLabel.setText("Level of Proficiency:");
        displayjPanel.add(leveljLabel);

        leveljComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        leveljComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                stylejComboBoxFocusLost(evt);
            }
        });
        displayjPanel.add(leveljComboBox);

        yearsjLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        yearsjLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        yearsjLabel.setText("Years of Dancing:");
        displayjPanel.add(yearsjLabel);

        yearsjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                yearsjTextFieldFocusLost(evt);
            }
        });
        yearsjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearsjTextFieldActionPerformed(evt);
            }
        });
        displayjPanel.add(yearsjTextField);

        phonejLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        phonejLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        phonejLabel.setText("Phone:");
        displayjPanel.add(phonejLabel);

        phonejTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                phonejTextFieldFocusLost(evt);
            }
        });
        phonejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonejTextFieldActionPerformed(evt);
            }
        });
        displayjPanel.add(phonejTextField);

        emailjLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        emailjLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        emailjLabel.setText("Email:");
        displayjPanel.add(emailjLabel);

        emailjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailjTextFieldFocusLost(evt);
            }
        });
        emailjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailjTextFieldActionPerformed(evt);
            }
        });
        displayjPanel.add(emailjTextField);

        controljPanel.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        savejButton.setBackground(new java.awt.Color(255, 204, 204));
        savejButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        savejButton.setMnemonic('S');
        savejButton.setText("Edit");
        savejButton.setToolTipText("Edit dancer");
        savejButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                stylejComboBoxFocusLost(evt);
            }
        });
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });
        controljPanel.add(savejButton);

        canceljButton.setBackground(new java.awt.Color(255, 204, 204));
        canceljButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        canceljButton.setMnemonic('C');
        canceljButton.setText("Cancel");
        canceljButton.setToolTipText("Dispose form");
        canceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButtonActionPerformed(evt);
            }
        });
        controljPanel.add(canceljButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(controljPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titlejPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(displayjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controljPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namejTextFieldActionPerformed

    private void yearsjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearsjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearsjTextFieldActionPerformed

    private void phonejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonejTextFieldActionPerformed

    private void emailjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailjTextFieldActionPerformed
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        savejButtonActionPerformed()
    * Description   Event handler for create a new dancer provided data inputed
    *               are valid
    * @author       <i>Abylay Dospayev</i>
    * Date          9/28/2022
    * History Log    
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        //Local variables needed
        String name = "";
        String style = "";
        String proficiency = "";
        int years = 0;
        String phone = "";
        String email="";
        
        //Read all input as strings
        String dancerName = namejTextField.getText();
        String styledancing = (String)stylejComboBox.getSelectedItem();
        String level = (String)leveljComboBox.getSelectedItem();
        String year = yearsjTextField.getText();
        String number = phonejTextField.getText();
        String mail = emailjTextField.getText();
        //call apropriate Validation methods
        if(!Validation.isValidName(dancerName)){
            errorMessage += "Invalid Dancer Name\n";
            namejTextField.requestFocus();
            error = true;
            namejTextField.setToolTipText(namejTextField.getToolTipText()+"--Invalid Dancer Name");
        }
        else if(!Validation.isInteger(year,0,MAX)){
            errorMessage += "Invalid Years of Dancing\n";
            namejTextField.requestFocus();
            error = true;
            yearsjTextField.setToolTipText(yearsjTextField.getToolTipText()+"--Invalid Years of Dancing");
        }
        else if (!Validation.isPhone(number)){
            errorMessage += "Invalid Dancer Phone Number\n";
            phonejTextField.requestFocus();
            error = true;
            phonejTextField.setToolTipText(phonejTextField.getToolTipText()+"--Invalid Dancer Phone Number");
        }
        else if (!Validation.isEmail(mail)){
            errorMessage += "Invalid Dancer Email address\n";
            emailjTextField.requestFocus();
            error = true;
            emailjTextField.setToolTipText(emailjTextField.getToolTipText()+"--Invalid Dancer Email addressr");
        }
        else 
            error = false;
        
        if(!error)
        {
            try
            {
                name = namejTextField.getText();
                style = (String)stylejComboBox.getSelectedItem();
                proficiency = (String)leveljComboBox.getSelectedItem();
                years = Integer.parseInt(yearsjTextField.getText());
                phone = phonejTextField.getText();
                email = emailjTextField.getText();
                newDancer = new Dancer(name, style, proficiency, years, phone, email);
                this.dispose(); //close form
            }
            catch(Exception ex)
            {
                throw  new RuntimeException("Error parsing input");
            }
        }
    }//GEN-LAST:event_savejButtonActionPerformed
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        cancelJButtonActionPerformed()
    * Description   Event handler for cancel adding a new dancer: do nothing and 
    *               leave newDancer as null
    * @param        evt ActionEvent
    * @author       <i>Abylay Dospayev</i>
    * Date          9/28/2022
    * History Log    
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_canceljButtonActionPerformed

    private void stylejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stylejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stylejComboBoxActionPerformed

    private void stylejComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stylejComboBoxFocusLost

    }//GEN-LAST:event_stylejComboBoxFocusLost
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        nameJTextFieldFocusLost()
    * Description   Event handler for the nameJTextField. It changes color if 
    *               input is not valid name
    * @param        evt Focus Event
    * @author       <i>Abylay Dospayev</i>
    * Date          9/28/2022
    * History Log    
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void namejTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namejTextFieldFocusLost
        //Set background textfiled color
        String input = namejTextField.getText();
        if(Validation.isValidName(input))
            namejTextField.setBackground(white);
        else 
            namejTextField.setBackground(pink);
    }//GEN-LAST:event_namejTextFieldFocusLost
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        yearsjTextFieldFocusLost()
    * Description   Event handler for the yearsjTextFieldFocusLost. It changes color if 
    *               input is not valid name
    * @param        evt Focus Event
    * @author       <i>Abylay Dospayev</i>
    * Date          9/28/2022
    * History Log    
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void yearsjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearsjTextFieldFocusLost
        //Set background textfiled color
        String input = yearsjTextField.getText();
        if(Validation.isInteger(input, 0, MAX))
            yearsjTextField.setBackground(white);
        else 
            yearsjTextField.setBackground(pink);
    }//GEN-LAST:event_yearsjTextFieldFocusLost
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        nameJTextFieldFocusLost()
    * Description   Event handler for the nameJTextField. It changes color if 
    *               input is not valid name
    * @param        evt Focus Event
    * @author       <i>Abylay Dospayev</i>
    * Date          9/28/2022
    * History Log    
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void phonejTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonejTextFieldFocusLost
        //Set background textfiled color
        String input = phonejTextField.getText();
        if(Validation.isPhone(input))
            phonejTextField.setBackground(white);
        else 
            phonejTextField.setBackground(pink);
    }//GEN-LAST:event_phonejTextFieldFocusLost
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        emailjTextFieldFocusLost()
    * Description   Event handler for the emailjTextFieldFocusLost. It changes color if 
    *               input is not valid name
    * @param        evt Focus Event
    * @author       <i>Abylay Dospayev</i>
    * Date          9/28/2022
    * History Log    
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void emailjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailjTextFieldFocusLost
        String input = emailjTextField.getText();
        if(Validation.isEmail(input))
            emailjTextField.setBackground(white);
        else 
            emailjTextField.setBackground(pink);
    }//GEN-LAST:event_emailjTextFieldFocusLost

    
    
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    * Method        getCity()
    * Description   Get method to return the newDancer
    * @return       newDancer Dancer
    * @author       <i>Abylay Dospayev</i>
    * Date          9/28/2022
    * History Log    
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    public Dancer getDancer()
    {
        return newDancer;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canceljButton;
    private javax.swing.JPanel controljPanel;
    private javax.swing.JPanel displayjPanel;
    private javax.swing.JLabel emailjLabel;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JLabel imagejLabel;
    private javax.swing.JComboBox<String> leveljComboBox;
    private javax.swing.JLabel leveljLabel;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JLabel phonejLabel;
    private javax.swing.JTextField phonejTextField;
    private javax.swing.JButton savejButton;
    private javax.swing.JComboBox<String> stylejComboBox;
    private javax.swing.JLabel stylejLabel;
    private javax.swing.JLabel titlejLabel;
    private javax.swing.JPanel titlejPanel;
    private javax.swing.JLabel yearsjLabel;
    private javax.swing.JTextField yearsjTextField;
    // End of variables declaration//GEN-END:variables
}
